version: '3.7'
services: 
  master:
    image: ${PREFIX}spark_master
    ports: 
      - '127.0.0.1:7077:7077'
      - '127.0.0.1:8080:8080'
  worker:
    environment:
      MASTER: master
      CORES: ${CONFIG_CORES}
      RAM: ${CONFIG_RAM}
    image: ${PREFIX}spark_worker
    depends_on: 
      - master
  livy:
    image: ${PREFIX}livy
    depends_on:
      - master
    ports:
      - '8998:8998'
  notebook:
    image: ${PREFIX}notebook
    ports:
      - '127.0.0.1:9999:9999'
    volumes:
      - 'workbooks:/workbooks'
    depends_on: 
      - livy
volumes: 
  workbooks:
    null